CREATE TABLE "annexure1" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"m_rainfall" double precision,
	"m_other_sources" double precision,
	"nm_rainfall" double precision,
	"nm_other_sources" double precision,
	"total_annual_recharge" double precision,
	"natural_discharge" double precision,
	"annual_extractable" double precision,
	"irri" double precision,
	"ind" double precision,
	"dom" double precision,
	"extraction_total" double precision,
	"allocation_domestic" double precision,
	"net_availability" double precision,
	"stage_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure2" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"m_rainfall" double precision,
	"m_other_sources" double precision,
	"nm_rainfall" double precision,
	"nm_other_sources" double precision,
	"total_annual" double precision,
	"natural_discharge" double precision,
	"annual_extractable" double precision,
	"ext_irri" double precision,
	"ext_ind" double precision,
	"ext_dom" double precision,
	"ext_total" double precision,
	"allocation_domestic" double precision,
	"net_availability" double precision,
	"stage_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure3a_state_categorization" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"total_assessed_units" double precision,
	"safe_count" double precision,
	"safe_percent" double precision,
	"semi_critical_count" double precision,
	"semi_critical_percent" double precision,
	"critical_count" double precision,
	"critical_percent" double precision,
	"over_exploited_count" double precision,
	"over_exploited_percent" double precision,
	"saline_count" double precision,
	"saline_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure3b_district_categorization" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"total_assessed_units" double precision,
	"safe_count" double precision,
	"safe_percent" double precision,
	"semi_critical_count" double precision,
	"semi_critical_percent" double precision,
	"critical_count" double precision,
	"critical_percent" double precision,
	"over_exploited_count" double precision,
	"over_exploited_percent" double precision,
	"saline_count" double precision,
	"saline_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure3c_state_extractable_resource" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"total_extractable_resource_ham" double precision,
	"safe_resource_ham" double precision,
	"safe_percent" double precision,
	"semi_critical_resource_ham" double precision,
	"semi_critical_percent" double precision,
	"critical_resource_ham" double precision,
	"critical_percent" double precision,
	"over_exploited_resource_ham" double precision,
	"over_exploited_percent" double precision,
	"saline_resource_ham" double precision,
	"saline_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure3d_district_extractable_resource" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"total_extractable_resource_ham" double precision,
	"safe_resource_ham" double precision,
	"safe_percent" double precision,
	"semi_critical_resource_ham" double precision,
	"semi_critical_percent" double precision,
	"critical_resource_ham" double precision,
	"critical_percent" double precision,
	"over_exploited_resource_ham" double precision,
	"over_exploited_percent" double precision,
	"saline_resource_ham" double precision,
	"saline_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure3e_state_area_categorization" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"total_geographical_area_sq_km" double precision,
	"recharge_worthy_area_sq_km" double precision,
	"safe_area_sq_km" double precision,
	"safe_percent" double precision,
	"semi_critical_area_sq_km" double precision,
	"semi_critical_percent" double precision,
	"critical_area_sq_km" double precision,
	"critical_percent" double precision,
	"over_exploited_area_sq_km" double precision,
	"over_exploited_percent" double precision,
	"saline_area_sq_km" double precision,
	"saline_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure3f_district_area_categorization" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"total_recharge_worthy_area_sq_km" double precision,
	"safe_area_sq_km" double precision,
	"safe_percent" double precision,
	"semi_critical_area_sq_km" double precision,
	"semi_critical_percent" double precision,
	"critical_area_sq_km" double precision,
	"critical_percent" double precision,
	"over_exploited_area_sq_km" double precision,
	"over_exploited_percent" double precision,
	"saline_area_sq_km" double precision,
	"saline_percent" double precision
);
--> statement-breakpoint
CREATE TABLE "annexure4a_categorized_units" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"semi_critical_unit" text,
	"critical_unit" text,
	"over_exploited_unit" text
);
--> statement-breakpoint
CREATE TABLE "annexure4b_quality_problems" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"fluoride_affected_unit" text,
	"arsenic_affected_unit" text,
	"salinity_affected_unit" text
);
--> statement-breakpoint
CREATE TABLE "attribute_detailed" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state_code" text,
	"district_code" text,
	"block_code" text,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"assessment_unit" text,
	"geo_area" double precision,
	"recharge_worthy_area" double precision,
	"recharge_rainfall_m" double precision,
	"recharge_other_m" double precision,
	"recharge_rainfall_nm" double precision,
	"recharge_other_nm" double precision,
	"annual_recharge" double precision,
	"natural_discharge" double precision,
	"annual_extractable" double precision,
	"extraction_irrigation" double precision,
	"extraction_industrial" double precision,
	"extraction_domestic" double precision,
	"extraction_total" double precision,
	"allocation_domestic_2025" double precision,
	"net_availability" double precision,
	"stage_percent" double precision,
	"categorization" text,
	"aquifer" text
);
--> statement-breakpoint
CREATE TABLE "attribute_summary" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"state" text NOT NULL,
	"over_exploited_count" double precision,
	"safe_count" double precision,
	"saline_count" double precision,
	"critical_count" double precision,
	"semi_critical_count" double precision,
	"total_count" double precision
);
--> statement-breakpoint
CREATE TABLE "central_report" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"serial_no" integer,
	"state" text NOT NULL,
	"district" text,
	"assessment_unit" text,
	"rainfall_contaminated" double precision,
	"rainfall_non_contaminated" double precision,
	"rainfall_poor_quality" double precision,
	"rainfall_total" double precision,
	"recharge_worthy_contaminated" double precision,
	"recharge_worthy_non_contaminated" double precision,
	"recharge_worthy_poor_quality" double precision,
	"recharge_worthy_total" double precision,
	"hilly_area" double precision,
	"geo_area_total" double precision,
	"rainfall_recharge_contaminated" double precision,
	"rainfall_recharge_non_contaminated" double precision,
	"rainfall_recharge_poor_quality" double precision,
	"rainfall_recharge_total" double precision,
	"recharge_other_monsoon" double precision,
	"non_monsoon_rainfall" double precision,
	"total_annual_recharge" double precision,
	"natural_discharge" double precision,
	"annual_extractable" double precision,
	"extraction_irrigation" double precision,
	"extraction_domestic" double precision,
	"extraction_industrial" double precision,
	"extraction_total" double precision,
	"stage_percent" double precision,
	"categorization" text
);
--> statement-breakpoint
CREATE TABLE "state_report" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" text NOT NULL,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"assessment_unit" text,
	"serial_no" integer,
	"rainfall_contaminated" double precision,
	"rainfall_non_contaminated" double precision,
	"rainfall_poor_quality" double precision,
	"rainfall_total" double precision,
	"recharge_worthy_contaminated" double precision,
	"recharge_worthy_non_contaminated" double precision,
	"recharge_worthy_poor_quality" double precision,
	"recharge_worthy_total" double precision,
	"hilly_area" double precision,
	"geo_area_total" double precision,
	"rainfall_recharge_contaminated" double precision,
	"rainfall_recharge_non_contaminated" double precision,
	"rainfall_recharge_poor_quality" double precision,
	"rainfall_recharge_total" double precision,
	"tanks_ponds_contaminated" double precision,
	"tanks_ponds_non_contaminated" double precision,
	"tanks_ponds_poor_quality" double precision,
	"tanks_ponds_total" double precision,
	"subtotal_contaminated" double precision,
	"subtotal_non_contaminated" double precision,
	"subtotal_poor_quality" double precision,
	"subtotal_total" double precision,
	"annual_gw_recharge_contaminated" double precision,
	"annual_gw_recharge_non_contaminated" double precision,
	"annual_gw_recharge_poor_quality" double precision,
	"annual_gw_recharge_total" double precision,
	"environmental_flow_contaminated" double precision,
	"environmental_flow_non_contaminated" double precision,
	"environmental_flow_poor_quality" double precision,
	"environmental_flow_total" double precision,
	"extractable_contaminated" double precision,
	"extractable_non_contaminated" double precision,
	"extractable_poor_quality" double precision,
	"extractable_total" double precision,
	"extraction_domestic_c" double precision,
	"extraction_domestic_nc" double precision,
	"extraction_domestic_pq" double precision,
	"extraction_domestic_total" double precision,
	"stage_extraction_contaminated" double precision,
	"stage_extraction_non_contaminated" double precision,
	"stage_extraction_poor_quality" double precision,
	"stage_extraction_total" double precision,
	"allocation_domestic_c" double precision,
	"allocation_domestic_nc" double precision,
	"allocation_domestic_pq" double precision,
	"allocation_domestic_total" double precision,
	"net_gw_availability_c" double precision,
	"net_gw_availability_nc" double precision,
	"net_gw_availability_pq" double precision,
	"net_gw_availability_total" double precision,
	"waterlogged" double precision,
	"flood_prone" double precision,
	"spring_discharge" double precision,
	"fresh_unconfined" double precision,
	"saline_unconfined" double precision,
	"fresh_confined" double precision,
	"saline_confined" double precision,
	"fresh_semi_confined" double precision,
	"saline_semi_confined" double precision
);
